runtime: nodejs18

handlers:
  # Serve static files
  - url: /static
    static_dir: build/static

  # Catch-all handler for index.html to support client-side routing
  - url: /.*
    script: auto